name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5     
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
        
    - name: Restore NuGet Packages
      run: nuget restore GitHubActionDemo.sln

    - name: Build app
      run: msbuild GitHubActionDemo.sln
      
    - name: Run UnitTests
      run: vstest.console.exe GitHubActionDemoUnitTests/bin/Debug/GitHubActionDemoUnitTests.dll

    - name: Build app for release
      run: msbuild GitHubActionDemo/GitHubActionDemo.csproj  /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GitHubDemo3'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FC0F082B831244F2911B33342ADD133D }}
        package: published\
