name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5     
      
    - name: Restore NuGet Packages
      run: nuget restore GitHubActionDemo.sln
      
    - name: Build app for release
      run: msbuild GitHubActionDemo.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .
        
    - name: Run UnitTests
      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe *test*.dll
