name: Build and deploy ASP.NET app to IIS - GitHubDemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Build app
        run: msbuild GitHubActionDemo.sln
      
      - name: Run UnitTests
        run: vstest.console.exe GitHubActionDemoUnitTests/bin/Debug/GitHubActionDemoUnitTests.dll 

      - name: Publish to folder
        run: msbuild GitHubActionDemo/GitHubActionDemo.csproj  /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app

      - name: Deploy to IIS
        shell: cmd
        run: |
          %windir%\system32\inetsrv\appcmd stop sites dotnet-webapp
          xcopy . C:/inetpub/wwwroot/dotnet-webapp /s /e /y
          %windir%\system32\inetsrv\appcmd start sites dotnet-webapp
